services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network  # Подключаемся к существующей сети вашего проекта

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - app-network  # Подключаемся к существующей сети

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # Добавьте эти переменные
      - XPACK_FLEET_REGISTRYURL=https://epr.elastic.co
      - XPACK_FLEET_ENABLED=false  # Временно отключите Fleet
      - SERVER_MAXPAYLOADBYTES=4194304
      - LOGGING_ROOT_LEVEL=debug
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "epr.elastic.co:34.120.127.130"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    volumes:
      - ./elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
    networks:
      - app-network  # Подключаемся к существующей сети

networks:
  app-network:
    external: true
    name: php_prgct_app-network  # Используем существующую сеть вашего проекта

volumes:
  elasticsearch-data: